### ISSUE TITLE
Does this need "Events"?

### ISSUE THREAD

**Issue by nitinthewiz** [digiwombat/WorldMuncher#5] opened 2017-03-17 19:38 UTC
Just thinking out loud here. I went through the code and didn't understand a single point where I could just add 'events' as a category. But I'm wondering if Events are a thing that WorldMuncher would benefit from.

**Comment by digiwombat** [comment] 2017-04-01 22:22
I'm currently (slowly) working on a more open ended system so you can add whatever sections you like.

That said, I've got a lot of books to write. Haha. So I'll be looking at implementing something like that. I feel like the nestable list system handles a lot of the base "timeline" ideas, so I likely won't add timelines outright.

But yeah! It'll get there.

EDIT: In the interests of keeping stuff compact, I'll mark this as a duplicate of #1.

**Closed as completed** 2017-04-01 22:24 UTC
Labels: duplicate
